//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoloskovApteka.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinePrescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicinePrescription()
        {
            this.MedicineSale = new HashSet<MedicineSale>();
        }
    
        public int PrescriptionID { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public int CustomerID { get; set; }
        public string DoctorFullName { get; set; }
        public string Diagnosis { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineSale> MedicineSale { get; set; }
    }
}
